@BibliotecaApi_HostAddress = http://localhost:5056
@Token = cole-o-token-aqui

POST {{BibliotecaApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@biblioteca.com",
  "password": "biblioteca123"
}

###

GET {{BibliotecaApi_HostAddress}}/api/auth/me
Authorization: Bearer {{Token}}
Accept: application/json

###

GET {{BibliotecaApi_HostAddress}}/api/books
Authorization: Bearer {{Token}}
Accept: application/json

###

GET {{BibliotecaApi_HostAddress}}/api/books/1
Authorization: Bearer {{Token}}
Accept: application/json

###

POST {{BibliotecaApi_HostAddress}}/api/books
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "title": "Arquitetura Limpa",
  "isbn": "9788550804606",
  "publishedYear": 2019,
  "genre": "Technology",
  "copiesAvailable": 4,
  "authorId": 2
}

###

PUT {{BibliotecaApi_HostAddress}}/api/books/1
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "title": "Dom Casmurro",
  "isbn": "9788535910663",
  "publishedYear": 1899,
  "genre": "Romance",
  "copiesAvailable": 5,
  "authorId": 1
}

###

PATCH {{BibliotecaApi_HostAddress}}/api/books/1/copies
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "copiesAvailable": 5
}

###

DELETE {{BibliotecaApi_HostAddress}}/api/books/3
Authorization: Bearer {{Token}}

###

GET {{BibliotecaApi_HostAddress}}/api/authors
Authorization: Bearer {{Token}}
Accept: application/json

###

POST {{BibliotecaApi_HostAddress}}/api/loans
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "bookId": 1,
  "memberId": 1
}

###

PUT {{BibliotecaApi_HostAddress}}/api/loans/1/return
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "returnDate": "2026-05-15"
}

###

GET {{BibliotecaApi_HostAddress}}/api/loans/overdue
Authorization: Bearer {{Token}}
Accept: application/json
